---
title: "Simple document"
output: github_document
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```
## Import some data

I want to import 'FAS_litters.csv'.

```{r}
litters_df = read_csv("data/FAS_litters.csv")
```

litters_df

I have imported the dataset. Now I want better names.

```{r}
names(litters_df)

litters_df = janitor::clean_names(litters_df)
```

```{r}
litters_df

head(litters_df, 20)
tail(litters_df)
```

```{r}
view(litters_df)
```
```{r}
skimr::skim(litters_df)
```
## Arguments in 'read_csv"

```{r, eval=FALSE}
  litters_df = 
    read_csv(
      "data/FAS_litters.csv",
      skip = 5,
      col_names = FALSE, 
      na = "Low8")
```

## Parsing Columns

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",

   col_types = cols(
   Group = col_character(),
   `Litter Number` = col_character(),
   `GD0 weight` = col_double(),
   `GD18 weight` = col_double(),
   `GD of Birth` = col_double(),
   `Pups born alive` = col_double(),
   `Pups dead @ birth` = col_double(),
   `Pups survive` = col_double()
 )
)
```

## Reading from Excel

```{r}
mlb11_df = read_excel("data/mlb11.xlsx")
```

```{r}
fellow_df = read_excel("data/LotR_Words.xlsx", range = "B3:D6")
```
## Read a SAS file

This is where I tried to read a SAS file and didn't

```{r, eval=FALSE}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```

##why to never use 'read.csv'

'read.csv' doesn't give 'tibble' and that's really bad

## how do I export data

```{r}
write_csv(fellow_df,"data/fellwship_words.csv")
```

